### ISSUE TITLE
mars-relay is a zombie process

### ISSUE THREAD

**Issue by 0323pin** [jzbor/marswm#18]
I've recently noticed, I usually have a zombie process running, see `top`on the screenshot

![2024-11-29-232311_1366x768_scrot](https://github.com/user-attachments/assets/51bbf135-b92d-446d-b43e-8fbb497e57b2)

I didn't want to open an issue straightaway, as I wanted to first confirm this happens all the time and it wasn't an isolated instance. But, it does happen all the time and the zombie is `mars-relay`

```
ps aux | grep "Z"
USER      PID %CPU %MEM     VSZ   RSS TTY   STAT STARTED    TIME COMMAND
pin     25769  0.0  0.0   12656  2376 pts/0 S+   11:23PM 0:00.01 /usr/bin/grep Z
pin      2549  0.0  0.0       0     0 ttyE0 Z          - 0:00.00 (mars-relay)
```

This is built from git-HEAD but, unfortunately I don't recall when this started or, if it has always been there.
Thoughts? Not that I'm worried about a zombie.

**Comment by jzbor** [comment]
Hm this probably depends on how you call `mars-relay`. A zombie process usually means the parent process has not picked up the child after it quit. This could either be for a valid reason or it could be a bug. So this probably has more to do with the shell scripts (or binaries?) that call `mars-relay`, than the program itself. If you have `htop` installed you can figure out it's parent by switching to the tree view.

**Comment by 0323pin** [comment]
Yeah, I know how zombie processes happen but, I was actually not aware `htop` could identify the parent. I will build it tonight and check what it says.

Although, ...
> So this probably has more to do with the shell scripts (or binaries?) that call mars-relay

I think I know where it comes from.

```
# marsbar.yaml

status_cmd: mars-relay set-status "$(env LC_TIME=sv_SE.UTF-8 date +'v%W %a %F')"
action_cmd: null
[...]
```

As I don't have a loop for the clock in date, the process is called once and never again. I'll have a look and let you know.

**Comment by jzbor** [comment]
https://github.com/jzbor/marswm/blob/ca5b249b60f3ac13dbf8f88a70989a933558bd51/marsbar/src/main.rs#L541

So, this seems to be the culprit. The process is only cleaned up _after_ the  eventloop exits (which probably is never). I think my assertion was that this was often times a process running during the full duration of the session, which is evidently not true. I am going to see what I can do about it...

**Comment by jzbor** [comment]
8a88ca730ae7163abcfdb8651a3838de88ed22ca should fix the issue. The process will not be collected immediately, but only after the next X11 event. This should however do the trick. I could not come up with a better solution without creating a separate thread.

[This](https://github.com/rust-lang/rust/issues/31289) looks like dropping is enough to detach a child process. So maybe we just drop the reference?

**Comment by 0323pin** [comment]
AFK until tonight but, I'll do a new build as soon as possible. Thanks for looking.

Maybe, I should just use a clock loop and check how much resources it consumes. I've never felt the need for it as I have a clock on my shell prompt.

**Comment by 0323pin** [comment]
@jzbor it's fixed, thank you!
