### ISSUE TITLE
Bump version?

### ISSUE THREAD

**Issue by 0323pin** [jzbor/marswm#19]
Hi,

**Disclaimer:** Honestly, I don't mind, as I'm running a build from git-HEAD but, I thought I'd bring it up anyway.

To me, it looks like the following:

 - marsbar: Clean up child processes in event loop
 - Update dependencies
 - Adding workflow_dispatch as workflow trigger
 - Adding open-docs app
 - Apply fixes suggested by clippy
 - marsbar: Cleaning up CreateWidget trait
 - Don't focus_direction if active is fullscreen
 - Adding error condition
 - Bugfix for x11_get_window_types
 - Align main clients horizontally in 'centered' layout
 - Implementing focus-direction
 - Implementing focus-direction binding for directional navigation
 - Adding 'centered' layout to fit ultrawide monitors
 - Adding attach_position option to marswm
 - Refactor libmars in order to make it easier to add new platforms down the road
 - Update examples/mars-status.sh to fix issue with HID device batteries
 - Fixing broken link in documentation

justify a new release. Just a thought.

**Comment by jzbor** [comment]
Hey, I have also thought about this and will definitely create a new release before the end of the year. Currently I am quite busy so it might take another week or two, as I want to make sure everything is in order and that I also have a little time available to update packaging for Nix and maybe Arch. On the 19th it will be one year since the last release so maybe that marks a nice date :D

**Comment by 0323pin** [comment]
> On the 19th it will be one year since the last release so maybe that marks a nice date :D

Sounds like a plan :)

If possible, could you please keep MSRV at 1.81? That's the newest Rust currently available on NetBSD. I'm on 1.83 myself but, the main tree won't move to 1.82 now because we are branching stable in two weeks.

**Comment by 0323pin** [comment]
If would like to consider, https://github.com/jzbor/marswm/pull/20

**Comment by jzbor** [comment]
Hey, I have released `0.6.0`. Your issue description provides a nice summary of recent changes. Thanks for your contributions both in terms of feedback and pull requests!

**Comment by 0323pin** [comment]
Thank you!

It will have to wait a few days. Until, the stable branch is cut but, I'll merge the package update as soon as possible.

**Comment by 0323pin** [comment]
@jzbor [merged](https://mail-index.netbsd.org/pkgsrc-changes/2024/12/20/msg312815.html)
