### ISSUE TITLE
Some minor bugs

### ISSUE THREAD

**Issue by 0323pin** [jzbor/marswm#3]
You are probably aware of these, if so feel free to close the issue.
Easier to explain with a screenshot ...

![stitch](https://user-images.githubusercontent.com/90570748/231539277-90162c2c-63da-4c4a-a063-f83293f78fae.png)

Screen 1: If `marsbar` is launched before any other window, the issue with the status command remains.
Screen 2: This never happens if `marsbar` is launched second to any other application.

Screen 3 & 4: The third tile is outside the screen edges.

**Comment by jzbor** [comment]
Re Screen 1 & 2: Hm this is odd. It works perfectly fine for me, although maybe something with tray icons changes the behavior

Re Screen 3 & 4: Hm this is really odd I never experienced that issue. What happens if you switch to a deck layout? And what, when you switch back? Is it the same issue with the clients laid out horizontally?

**Comment by 0323pin** [comment]
You can find all my config files [here](https://codeberg.org/pin/netbsd/src/branch/main/.config/marswm) 

> What happens if you switch to a deck layout? And what, when you switch back

The third tile is still outside the edge of the screen.

> Is it the same issue with the clients laid out horizontally?

Yes but, outside to the right instead of bottom.

Obviously, if I add a forth client, it's this one that is outside.
This doesn't happen when only two clients are on display.

As for the bar, I'm launching it through a keybinding, so it's not an issue.

**Comment by jzbor** [comment]
This seems to be an issue with the gaps. This commit should fix it.

**Comment by 0323pin** [comment]
Yes, it's fixed. Thank you!

**Comment by 0323pin** [comment]
Indeed it is 👍 
I got so used to launch `marsbar` through a keybinding, that I wouldn't have known.

I still have one wish though 😆

**Comment by jzbor** [comment]
> I still have one wish though 😆

That being? (No guarantees that I can currently implement it though, especially if it requires substantial changes)

**Comment by 0323pin** [comment]
There's no rush. Indicators for ocupied tags, I've describe it [here](https://github.com/jzbor/marswm/issues/1#issuecomment-1485059254).
