### ISSUE TITLE
INSTALLATION.md points to non-available file

### ISSUE THREAD

**Issue by 0323pin** [jzbor/marswm#9]
> `marswm` is currently not officially packaged for Nix. You can use the derivation in [examples/default.nix](https://github.com/jzbor/marswm/blob/master/examples/default.nix) to install it on your machine.

![2023-07-05-210819_1366x768_scrot](https://github.com/jzbor/marswm/assets/90570748/f7a86ee4-6ffb-40b4-ac79-1cde422c41fb)

**Comment by jzbor** [comment]
Thanks for reporting!
